# Generated by Django 5.1.2 on 2024-11-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flights_from', to='flights.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flights_to', to='flights.city')),
            ],
        ),
        migrations.CreateModel(
            name='FlightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_on', models.DateTimeField()),
                ('arrival_on', models.DateTimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.flight')),
            ],
        ),
    ]
